export type OrderStatus = 'IN_PROGRESS' | 'COMPLETE' | 'PENDING' | 'APPROVED' | 'REJECTED'

export interface OrderItem {
  orderId: string
  userName: string
  userImage: string
  projectName: string
  address: string
  date: string
  status: OrderStatus
  status_text: string
  status_color: string
  dark_status_color?: string
  [key: string]: unknown
}

export const orders: OrderItem[] = [
  {
    orderId: '#CM9081',
    userName: 'Natali Craig',
    userImage: 'Female15.png',
    projectName: 'Landing Page',
    address: 'Meadow Lane Oakland',
    date: 'Just now',
    status: 'IN_PROGRESS',
    status_text: 'In Progress',
    status_color: '#8a8cd9',
  },
  {
    orderId: '#CM9082',
    userName: 'Kate Morrison',
    userImage: 'Female09.png',
    projectName: 'CRM Admin Pages',
    address: 'Larry San Francisco',
    date: 'A minute ago',
    status: 'COMPLETE',
    status_text: 'Complete',
    status_color: '#4aa785',
  },
  {
    orderId: '#CM9083',
    userName: 'Drew Cano',
    userImage: 'Male08.png',
    projectName: 'Client Project',
    address: 'Bagwell Avenue Ocala',
    date: '1 hour ago',
    status: 'PENDING',
    status_text: 'Pending',
    status_color: '#59a8d4',
  },
  {
    orderId: '#CM9084',
    userName: 'Orlando Diggs',
    userImage: 'Male06.png',
    projectName: 'Admin Dashboard',
    address: 'Washburn Baton Rouge',
    date: 'Yesterday',
    status: 'APPROVED',
    status_text: 'Approved',
    status_color: '#ffc555',
  },
  {
    orderId: '#CM9085',
    userName: 'Andie Lane',
    userImage: 'Female08.png',
    projectName: 'App Landing Page',
    address: 'Nest Lane Olivette',
    date: 'Feb 2, 2023',
    status: 'REJECTED',
    status_text: 'Rejected',
    status_color: '#1c1c1c',
    dark_status_color: 'rgba(255, 255, 255, 0.4)',
  },
  // repeat to have more rows
  {
    orderId: '#CM9086',
    userName: 'Natali Craig',
    userImage: 'Female15.png',
    projectName: 'Landing Page',
    address: 'Meadow Lane Oakland',
    date: 'Just now',
    status: 'IN_PROGRESS',
    status_text: 'In Progress',
    status_color: '#8a8cd9',
  },
  {
    orderId: '#CM9087',
    userName: 'Kate Morrison',
    userImage: 'Female09.png',
    projectName: 'CRM Admin Pages',
    address: 'Larry San Francisco',
    date: 'A minute ago',
    status: 'COMPLETE',
    status_text: 'Complete',
    status_color: '#4aa785',
  },
  {
    orderId: '#CM9088',
    userName: 'Drew Cano',
    userImage: 'Male08.png',
    projectName: 'Client Project',
    address: 'Bagwell Avenue Ocala',
    date: '1 hour ago',
    status: 'PENDING',
    status_text: 'Pending',
    status_color: '#59a8d4',
  },
  {
    orderId: '#CM9089',
    userName: 'Orlando Diggs',
    userImage: 'Male06.png',
    projectName: 'Admin Dashboard',
    address: 'Washburn Baton Rouge',
    date: 'Yesterday',
    status: 'APPROVED',
    status_text: 'Approved',
    status_color: '#ffc555',
  },
  {
    orderId: '#CM9090',
    userName: 'Andie Lane',
    userImage: 'Female08.png',
    projectName: 'App Landing Page',
    address: 'Nest Lane Olivette',
    date: 'Feb 2, 2023',
    status: 'REJECTED',
    status_text: 'Rejected',
    status_color: '#1c1c1c',
    dark_status_color: 'rgba(255, 255, 255, 0.4)',
  },
  {
    orderId: '#CM9091',
    userName: 'Sarah Johnson',
    userImage: 'Female05.png',
    projectName: 'E-commerce Site',
    address: 'Main Street Chicago',
    date: 'Feb 1, 2023',
    status: 'IN_PROGRESS',
    status_text: 'In Progress',
    status_color: '#8a8cd9',
  },
  {
    orderId: '#CM9092',
    userName: 'Mike Davis',
    userImage: 'Male07.png',
    projectName: 'Portfolio Website',
    address: 'Oak Avenue Portland',
    date: 'Jan 30, 2023',
    status: 'COMPLETE',
    status_text: 'Complete',
    status_color: '#4aa785',
  },
  {
    orderId: '#CM9093',
    userName: 'Emma Wilson',
    userImage: 'Female15.png',
    projectName: 'Mobile App UI',
    address: 'Pine Street Seattle',
    date: 'Jan 28, 2023',
    status: 'PENDING',
    status_text: 'Pending',
    status_color: '#59a8d4',
  },
  {
    orderId: '#CM9094',
    userName: 'James Brown',
    userImage: 'Male11.png',
    projectName: 'Corporate Website',
    address: 'Cedar Road Denver',
    date: 'Jan 25, 2023',
    status: 'APPROVED',
    status_text: 'Approved',
    status_color: '#ffc555',
  },
  {
    orderId: '#CM9095',
    userName: 'Lisa Anderson',
    userImage: 'Female09.png',
    projectName: 'Blog Platform',
    address: 'Maple Drive Austin',
    date: 'Jan 20, 2023',
    status: 'REJECTED',
    status_text: 'Rejected',
    status_color: '#1c1c1c',
    dark_status_color: 'rgba(255, 255, 255, 0.4)',
  },
  {
    orderId: '#CM9096',
    userName: 'Robert Garcia',
    userImage: 'Male06.png',
    projectName: 'SaaS Dashboard',
    address: 'Elm Street Boston',
    date: 'Jan 18, 2023',
    status: 'IN_PROGRESS',
    status_text: 'In Progress',
    status_color: '#8a8cd9',
  },
  {
    orderId: '#CM9097',
    userName: 'Jennifer Lee',
    userImage: 'Female08.png',
    projectName: 'News Portal',
    address: 'Birch Lane Miami',
    date: 'Jan 15, 2023',
    status: 'COMPLETE',
    status_text: 'Complete',
    status_color: '#4aa785',
  },
  {
    orderId: '#CM9098',
    userName: 'David Martinez',
    userImage: 'Male08.png',
    projectName: 'Learning Platform',
    address: 'Spruce Road Phoenix',
    date: 'Jan 12, 2023',
    status: 'PENDING',
    status_text: 'Pending',
    status_color: '#59a8d4',
  },
  {
    orderId: '#CM9099',
    userName: 'Amanda Taylor',
    userImage: 'Female15.png',
    projectName: 'Social Network',
    address: 'Willow Court Nashville',
    date: 'Jan 10, 2023',
    status: 'APPROVED',
    status_text: 'Approved',
    status_color: '#ffc555',
  },
  {
    orderId: '#CM9100',
    userName: 'Christopher White',
    userImage: 'Male07.png',
    projectName: 'Tech Startup Site',
    address: 'Poplar Street Las Vegas',
    date: 'Jan 8, 2023',
    status: 'REJECTED',
    status_text: 'Rejected',
    status_color: '#1c1c1c',
    dark_status_color: 'rgba(255, 255, 255, 0.4)',
  },
]
